import React, { useState, useEffect } from 'react';
import { Download, FileCode, Eye, Copy, CheckCircle, Folder, File, Zap } from 'lucide-react';
import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import { ProjectRequirement, TechStack, GeneratedCode } from '../types';
import { generateCodeWithAI } from '../utils/aiCodeGenerator';

interface CodeGenerationProps {
  requirements: ProjectRequirement[];
  techStack: TechStack[];
  onNext: () => void;
  onBack: () => void;
}

export const CodeGeneration: React.FC<CodeGenerationProps> = ({
  requirements,
  techStack,
  onNext,
  onBack
}) => {
  const [generatedFiles, setGeneratedFiles] = useState<GeneratedCode[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [selectedFile, setSelectedFile] = useState<string>('');
  const [viewMode, setViewMode] = useState<'tree' | 'list'>('tree');

  useEffect(() => {
    generateCode();
  }, []);

  const generateCode = async () => {
    setIsGenerating(true);

    try {
      const files = await generateCodeWithAI(requirements, techStack);
      setGeneratedFiles(files);
      setSelectedFile(files[0].filename);
    } catch (error) {
      console.error('Error generating code:', error);
      // Fallback to mock data on error
      setGeneratedFiles(getMockFiles());
      setSelectedFile(getMockFiles()[0].filename);
    } finally {
      setIsGenerating(false);
    }
  };

  const getMockFiles = (): GeneratedCode[] => {
    return [
      {
        filename: 'package.json',
        language: 'json',
        content: `{
  "name": "generated-project",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    ${techStack.map(tech => {
      switch(tech.id) {
        case 'react': return `"react": "^${tech.version}",\n    "react-dom": "^${tech.version}"`;
        case 'typescript': return `"typescript": "^${tech.version}"`;
        case 'nodejs': return `"express": "^4.18.0"`;
        default: return `"${tech.name.toLowerCase()}": "^${tech.version}"`;
      }
    }).join(',\n    ')}
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}`,
        explanation: 'Project configuration with dependencies and scripts'
      },
      {
        filename: 'public/index.html',
        language: 'html',
        content: `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="icon" href="%PUBLIC_URL%/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#000000" />
    <meta name="description" content="Generated by jellyfishAI Platform" />
    <title>Generated App</title>
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>
  </body>
</html>`,
        explanation: 'Main HTML template for the React application'
      },
      {
        filename: 'src/index.tsx',
        language: 'typescript',
        content: `import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import App from './App';

const root = ReactDOM.createRoot(
  document.getElementById('root') as HTMLElement
);

root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);`,
        explanation: 'Entry point for the React application'
      },
      {
        filename: 'src/App.tsx',
        language: 'typescript',
        content: `import React, { useState, useEffect } from 'react';
import './App.css';

interface User {
  id: number;
  name: string;
  email: string;
}

const App: React.FC = () => {
  const [users, setUsers] = useState<User[]>([]);
  const [loading, setLoading] = useState(true);
  const [newUser, setNewUser] = useState({ name: '', email: '' });

  useEffect(() => {
    // Simulate API call
    setTimeout(() => {
      setUsers([
        { id: 1, name: 'John Doe', email: 'john@example.com' },
        { id: 2, name: 'Jane Smith', email: 'jane@example.com' }
      ]);
      setLoading(false);
    }, 1000);
  }, []);

  const addUser = () => {
    if (newUser.name && newUser.email) {
      const user: User = {
        id: Date.now(),
        name: newUser.name,
        email: newUser.email
      };
      setUsers([...users, user]);
      setNewUser({ name: '', email: '' });
    }
  };

  const deleteUser = (id: number) => {
    setUsers(users.filter(user => user.id !== id));
  };

  if (loading) {
    return (
      <div className="loading">
        <div className="spinner"></div>
        <p>Loading...</p>
      </div>
    );
  }

  return (
    <div className="App">
      <header className="App-header">
        <h1>User Management System</h1>
        <p>Generated by jellyfishAI Platform</p>
      </header>

      <main className="main-content">
        <section className="add-user-section">
          <h2>Add New User</h2>
          <div className="form-group">
            <input
              type="text"
              placeholder="Name"
              value={newUser.name}
              onChange={(e) => setNewUser({ ...newUser, name: e.target.value })}
            />
            <input
              type="email"
              placeholder="Email"
              value={newUser.email}
              onChange={(e) => setNewUser({ ...newUser, email: e.target.value })}
            />
            <button onClick={addUser} className="add-btn">
              Add User
            </button>
          </div>
        </section>

        <section className="users-section">
          <h2>Users ({users.length})</h2>
          <div className="users-grid">
            {users.map(user => (
              <div key={user.id} className="user-card">
                <h3>{user.name}</h3>
                <p>{user.email}</p>
                <button 
                  onClick={() => deleteUser(user.id)}
                  className="delete-btn"
                >
                  Delete
                </button>
              </div>
            ))}
          </div>
        </section>
      </main>
    </div>
  );
};

export default App;`,
        explanation: 'Main application component with user management functionality'
      },
      {
        filename: 'src/App.css',
        language: 'css',
        content: `.App {
  text-align: center;
  min-height: 100vh;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
}

.App-header {
  background-color: rgba(255, 255, 255, 0.1);
  padding: 20px;
  color: white;
  backdrop-filter: blur(10px);
  border-bottom: 1px solid rgba(255, 255, 255, 0.2);
}

.App-header h1 {
  margin: 0 0 10px 0;
  font-size: 2.5rem;
  font-weight: 700;
}

.App-header p {
  margin: 0;
  opacity: 0.8;
}

.main-content {
  padding: 40px 20px;
  max-width: 1200px;
  margin: 0 auto;
}

.add-user-section {
  background: rgba(255, 255, 255, 0.1);
  backdrop-filter: blur(10px);
  border-radius: 20px;
  padding: 30px;
  margin-bottom: 40px;
  border: 1px solid rgba(255, 255, 255, 0.2);
}

.add-user-section h2 {
  color: white;
  margin-bottom: 20px;
  font-size: 1.8rem;
}

.form-group {
  display: flex;
  gap: 15px;
  justify-content: center;
  flex-wrap: wrap;
}

.form-group input {
  padding: 12px 16px;
  border: none;
  border-radius: 10px;
  background: rgba(255, 255, 255, 0.9);
  font-size: 16px;
  min-width: 200px;
  transition: all 0.3s ease;
}

.form-group input:focus {
  outline: none;
  transform: translateY(-2px);
  box-shadow: 0 5px 15px rgba(0, 0, 0, 0.2);
}

.add-btn {
  padding: 12px 24px;
  background: linear-gradient(45deg, #4CAF50, #45a049);
  color: white;
  border: none;
  border-radius: 10px;
  font-size: 16px;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.3s ease;
}

.add-btn:hover {
  transform: translateY(-2px);
  box-shadow: 0 5px 15px rgba(76, 175, 80, 0.4);
}

.users-section h2 {
  color: white;
  margin-bottom: 30px;
  font-size: 1.8rem;
}

.users-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
  gap: 20px;
}

.user-card {
  background: rgba(255, 255, 255, 0.1);
  backdrop-filter: blur(10px);
  border-radius: 15px;
  padding: 25px;
  border: 1px solid rgba(255, 255, 255, 0.2);
  transition: all 0.3s ease;
}

.user-card:hover {
  transform: translateY(-5px);
  box-shadow: 0 10px 25px rgba(0, 0, 0, 0.2);
}

.user-card h3 {
  color: white;
  margin: 0 0 10px 0;
  font-size: 1.3rem;
}

.user-card p {
  color: rgba(255, 255, 255, 0.8);
  margin: 0 0 15px 0;
}

.delete-btn {
  padding: 8px 16px;
  background: linear-gradient(45deg, #f44336, #d32f2f);
  color: white;
  border: none;
  border-radius: 8px;
  cursor: pointer;
  font-size: 14px;
  transition: all 0.3s ease;
}

.delete-btn:hover {
  transform: translateY(-2px);
  box-shadow: 0 5px 15px rgba(244, 67, 54, 0.4);
}

.loading {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100vh;
  color: white;
}

.spinner {
  width: 50px;
  height: 50px;
  border: 4px solid rgba(255, 255, 255, 0.3);
  border-top: 4px solid white;
  border-radius: 50%;
  animation: spin 1s linear infinite;
  margin-bottom: 20px;
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

@media (max-width: 768px) {
  .form-group {
    flex-direction: column;
    align-items: center;
  }
  
  .form-group input {
    width: 100%;
    max-width: 300px;
  }
  
  .users-grid {
    grid-template-columns: 1fr;
  }
}`,
        explanation: 'Styling for the application with modern design and animations'
      },
      {
        filename: 'src/index.css',
        language: 'css',
        content: `body {
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
    'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue',
    sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

code {
  font-family: source-code-pro, Menlo, Monaco, Consolas, 'Courier New',
    monospace;
}

* {
  box-sizing: border-box;
}

html {
  scroll-behavior: smooth;
}`,
        explanation: 'Global CSS reset and base styles'
      },
      {
        filename: 'src/components/UserCard.tsx',
        language: 'typescript',
        content: `import React from 'react';

interface User {
  id: number;
  name: string;
  email: string;
}

interface UserCardProps {
  user: User;
  onDelete: (id: number) => void;
}

const UserCard: React.FC<UserCardProps> = ({ user, onDelete }) => {
  return (
    <div className="user-card">
      <div className="user-avatar">
        {user.name.charAt(0).toUpperCase()}
      </div>
      <h3>{user.name}</h3>
      <p>{user.email}</p>
      <div className="user-actions">
        <button className="edit-btn">Edit</button>
        <button 
          onClick={() => onDelete(user.id)}
          className="delete-btn"
        >
          Delete
        </button>
      </div>
    </div>
  );
};

export default UserCard;`,
        explanation: 'Reusable user card component with TypeScript interfaces'
      },
      {
        filename: 'src/hooks/useUsers.ts',
        language: 'typescript',
        content: `import { useState, useEffect } from 'react';

interface User {
  id: number;
  name: string;
  email: string;
}

export const useUsers = () => {
  const [users, setUsers] = useState<User[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetchUsers();
  }, []);

  const fetchUsers = async () => {
    try {
      setLoading(true);
      // Simulate API call
      await new Promise(resolve => setTimeout(resolve, 1000));
      
      const mockUsers: User[] = [
        { id: 1, name: 'John Doe', email: 'john@example.com' },
        { id: 2, name: 'Jane Smith', email: 'jane@example.com' },
        { id: 3, name: 'Bob Johnson', email: 'bob@example.com' }
      ];
      
      setUsers(mockUsers);
      setError(null);
    } catch (err) {
      setError('Failed to fetch users');
    } finally {
      setLoading(false);
    }
  };

  const addUser = (user: Omit<User, 'id'>) => {
    const newUser: User = {
      id: Date.now(),
      ...user
    };
    setUsers(prev => [...prev, newUser]);
  };

  const deleteUser = (id: number) => {
    setUsers(prev => prev.filter(user => user.id !== id));
  };

  const updateUser = (id: number, updates: Partial<User>) => {
    setUsers(prev => prev.map(user => 
      user.id === id ? { ...user, ...updates } : user
    ));
  };

  return {
    users,
    loading,
    error,
    addUser,
    deleteUser,
    updateUser,
    refetch: fetchUsers
  };
};`,
        explanation: 'Custom React hook for user management with TypeScript'
      },
      {
        filename: 'src/utils/api.ts',
        language: 'typescript',
        content: `const API_BASE_URL = process.env.REACT_APP_API_URL || 'http://localhost:3001/api';

interface ApiResponse<T> {
  data: T;
  message: string;
  success: boolean;
}

class ApiClient {
  private baseURL: string;

  constructor(baseURL: string) {
    this.baseURL = baseURL;
  }

  private async request<T>(
    endpoint: string,
    options: RequestInit = {}
  ): Promise<ApiResponse<T>> {
    const url = \`\${this.baseURL}\${endpoint}\`;
    
    const config: RequestInit = {
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
      ...options,
    };

    try {
      const response = await fetch(url, config);
      
      if (!response.ok) {
        throw new Error(\`HTTP error! status: \${response.status}\`);
      }
      
      const data = await response.json();
      return data;
    } catch (error) {
      console.error('API request failed:', error);
      throw error;
    }
  }

  async get<T>(endpoint: string): Promise<ApiResponse<T>> {
    return this.request<T>(endpoint, { method: 'GET' });
  }

  async post<T>(endpoint: string, data: any): Promise<ApiResponse<T>> {
    return this.request<T>(endpoint, {
      method: 'POST',
      body: JSON.stringify(data),
    });
  }

  async put<T>(endpoint: string, data: any): Promise<ApiResponse<T>> {
    return this.request<T>(endpoint, {
      method: 'PUT',
      body: JSON.stringify(data),
    });
  }

  async delete<T>(endpoint: string): Promise<ApiResponse<T>> {
    return this.request<T>(endpoint, { method: 'DELETE' });
  }
}

export const apiClient = new ApiClient(API_BASE_URL);

// User API functions
export const userApi = {
  getUsers: () => apiClient.get('/users'),
  createUser: (user: any) => apiClient.post('/users', user),
  updateUser: (id: number, user: any) => apiClient.put(\`/users/\${id}\`, user),
  deleteUser: (id: number) => apiClient.delete(\`/users/\${id}\`),
};`,
        explanation: 'API client utility with TypeScript for making HTTP requests'
      },
      {
        filename: 'README.md',
        language: 'markdown',
        content: `# Generated Project

This project was generated by **jellyfishAI Platform** - a revolutionary GenAI-powered development platform.

## 🚀 Features

- **User Management System**: Add, view, and delete users
- **Modern React**: Built with React 18 and TypeScript
- **Responsive Design**: Works on all devices
- **Custom Hooks**: Reusable logic with useUsers hook
- **API Integration**: Ready for backend integration
- **Modern Styling**: Beautiful gradient design with animations

## 📦 Tech Stack

${techStack.map(tech => `- **${tech.name}** v${tech.version} - ${tech.description}`).join('\n')}

## 🛠️ Installation

1. Install dependencies:
\`\`\`bash
npm install
\`\`\`

2. Start the development server:
\`\`\`bash
npm start
\`\`\`

3. Open [http://localhost:3000](http://localhost:3000) to view it in the browser.

## 📁 Project Structure

\`\`\`
src/
├── components/          # Reusable React components
│   └── UserCard.tsx    # User card component
├── hooks/              # Custom React hooks
│   └── useUsers.ts     # User management hook
├── utils/              # Utility functions
│   └── api.ts          # API client
├── App.tsx             # Main application component
├── App.css             # Application styles
├── index.tsx           # Application entry point
└── index.css           # Global styles
\`\`\`

## 🎯 Requirements Implemented

${requirements.map((req, index) => `${index + 1}. **${req.title}** (${req.priority} priority)
   - ${req.description}
   - Category: ${req.category}`).join('\n\n')}

## 🚀 Available Scripts

- \`npm start\` - Runs the app in development mode
- \`npm test\` - Launches the test runner
- \`npm run build\` - Builds the app for production
- \`npm run eject\` - Ejects from Create React App

## 🌟 Generated by jellyfishAI

This project was automatically generated based on your requirements using advanced AI technology. The code follows best practices and is production-ready.

### Key Features:
- ✅ TypeScript for type safety
- ✅ Modern React patterns
- ✅ Responsive design
- ✅ Custom hooks
- ✅ API integration ready
- ✅ Clean code structure

## 📝 Next Steps

1. **Backend Integration**: Connect to your preferred backend API
2. **Authentication**: Add user authentication system
3. **Database**: Set up database for persistent storage
4. **Testing**: Add unit and integration tests
5. **Deployment**: Deploy to your preferred hosting platform

---

**Generated with ❤️ by jellyfishAI Platform**`,
        explanation: 'Project documentation with setup instructions and feature overview'
      },
      {
        filename: '.gitignore',
        language: 'text',
        content: `# Dependencies
node_modules/
/.pnp
.pnp.js

# Testing
/coverage

# Production
/build

# Environment variables
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# Logs
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# IDE
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Temporary files
*.tmp
*.temp`,
        explanation: 'Git ignore file to exclude unnecessary files from version control'
      }
    ];

    setGeneratedFiles(files);
    setSelectedFile(files[0].filename);
    setIsGenerating(false);
  };

  const downloadAllFiles = async () => {
    const zip = new JSZip();
    
    generatedFiles.forEach((file) => {
      // Create folder structure
      const parts = file.filename.split('/');
      if (parts.length > 1) {
        const folder = parts.slice(0, -1).join('/');
        const fileName = parts[parts.length - 1];
        zip.folder(folder)?.file(fileName, file.content);
      } else {
        zip.file(file.filename, file.content);
      }
    });

    const content = await zip.generateAsync({ type: 'blob' });
    saveAs(content, `generated-project-${Date.now()}.zip`);
  };

  const copyToClipboard = (content: string) => {
    navigator.clipboard.writeText(content);
  };

  const getFileIcon = (filename: string) => {
    const ext = filename.split('.').pop()?.toLowerCase();
    switch (ext) {
      case 'tsx':
      case 'ts':
        return '📘';
      case 'css':
        return '🎨';
      case 'json':
        return '📋';
      case 'html':
        return '🌐';
      case 'md':
        return '📝';
      default:
        return '📄';
    }
  };

  const organizeFilesByFolder = () => {
    const folders: { [key: string]: GeneratedCode[] } = {};
    
    generatedFiles.forEach(file => {
      const parts = file.filename.split('/');
      if (parts.length > 1) {
        const folder = parts[0];
        if (!folders[folder]) folders[folder] = [];
        folders[folder].push(file);
      } else {
        if (!folders['root']) folders['root'] = [];
        folders['root'].push(file);
      }
    });
    
    return folders;
  };

  const selectedFileContent = generatedFiles.find(f => f.filename === selectedFile);
  const folders = organizeFilesByFolder();

  return (
    <div className="max-w-7xl mx-auto p-6">
      <div className="text-center mb-8">
        <h2 className="text-3xl font-bold text-white mb-4">Generated Code Files</h2>
        <p className="text-white/70 text-lg">
          AI has generated {generatedFiles.length} production-ready files based on your requirements.
        </p>
      </div>

      {isGenerating ? (
        <div className="bg-white/10 backdrop-blur-md rounded-2xl p-8 border border-white/20 text-center">
          <div className="w-16 h-16 border-4 border-indigo-500 border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
          <h3 className="text-white font-semibold mb-2">AI is generating your code...</h3>
          <p className="text-white/70">
            Analyzing requirements, selecting optimal patterns, and creating production-ready files
          </p>
        </div>
      ) : (
        <>
          {/* Download Section */}
          <div className="bg-gradient-to-r from-green-500/20 to-emerald-500/20 backdrop-blur-md rounded-2xl p-6 border border-green-500/30 mb-8">
            <div className="flex items-center justify-between">
              <div className="flex items-center space-x-4">
                <div className="p-3 bg-green-500/20 rounded-full">
                  <CheckCircle className="w-8 h-8 text-green-400" />
                </div>
                <div>
                  <h3 className="text-white font-semibold text-xl">Code Generation Complete!</h3>
                  <p className="text-white/70">
                    {generatedFiles.length} files generated • Ready for download and deployment
                  </p>
                </div>
              </div>
              <button
                onClick={downloadAllFiles}
                className="bg-gradient-to-r from-green-500 to-emerald-600 hover:from-green-600 hover:to-emerald-700 text-white px-8 py-4 rounded-xl font-semibold transition-all duration-200 transform hover:scale-105 flex items-center space-x-3 shadow-lg"
              >
                <Download className="w-5 h-5" />
                <span>Download ZIP</span>
              </button>
            </div>
          </div>

          {/* File Explorer */}
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-8">
            {/* File Tree */}
            <div className="bg-white/10 backdrop-blur-md rounded-2xl p-6 border border-white/20">
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-white font-semibold">Project Files</h3>
                <div className="flex items-center space-x-2">
                  <button
                    onClick={() => setViewMode('tree')}
                    className={`p-2 rounded-lg transition-colors ${viewMode === 'tree' ? 'bg-indigo-500/30 text-white' : 'text-white/60 hover:text-white'}`}
                  >
                    <Folder className="w-4 h-4" />
                  </button>
                  <button
                    onClick={() => setViewMode('list')}
                    className={`p-2 rounded-lg transition-colors ${viewMode === 'list' ? 'bg-indigo-500/30 text-white' : 'text-white/60 hover:text-white'}`}
                  >
                    <File className="w-4 h-4" />
                  </button>
                </div>
              </div>

              <div className="space-y-2 max-h-96 overflow-y-auto">
                {viewMode === 'tree' ? (
                  Object.entries(folders).map(([folder, files]) => (
                    <div key={folder}>
                      <div className="flex items-center space-x-2 text-white/80 font-medium mb-2">
                        <Folder className="w-4 h-4" />
                        <span>{folder === 'root' ? 'Root' : folder}</span>
                      </div>
                      <div className="ml-6 space-y-1">
                        {files.map((file) => (
                          <button
                            key={file.filename}
                            onClick={() => setSelectedFile(file.filename)}
                            className={`w-full text-left p-2 rounded-lg transition-all duration-200 flex items-center space-x-2 ${
                              selectedFile === file.filename
                                ? 'bg-indigo-500/30 text-white'
                                : 'text-white/70 hover:bg-white/10 hover:text-white'
                            }`}
                          >
                            <span className="text-lg">{getFileIcon(file.filename)}</span>
                            <span className="text-sm">{file.filename.split('/').pop()}</span>
                          </button>
                        ))}
                      </div>
                    </div>
                  ))
                ) : (
                  generatedFiles.map((file) => (
                    <button
                      key={file.filename}
                      onClick={() => setSelectedFile(file.filename)}
                      className={`w-full text-left p-3 rounded-lg transition-all duration-200 flex items-center space-x-3 ${
                        selectedFile === file.filename
                          ? 'bg-indigo-500/30 text-white'
                          : 'text-white/70 hover:bg-white/10 hover:text-white'
                      }`}
                    >
                      <span className="text-lg">{getFileIcon(file.filename)}</span>
                      <div className="flex-1">
                        <div className="font-medium">{file.filename}</div>
                        <div className="text-xs opacity-70 capitalize">{file.language}</div>
                      </div>
                    </button>
                  ))
                )}
              </div>
            </div>

            {/* Code Viewer */}
            <div className="lg:col-span-2 bg-white/10 backdrop-blur-md rounded-2xl border border-white/20 overflow-hidden">
              {selectedFileContent && (
                <>
                  <div className="p-4 border-b border-white/20 flex items-center justify-between">
                    <div className="flex items-center space-x-3">
                      <span className="text-lg">{getFileIcon(selectedFileContent.filename)}</span>
                      <div>
                        <h4 className="text-white font-medium">{selectedFileContent.filename}</h4>
                        <p className="text-white/60 text-sm capitalize">{selectedFileContent.language}</p>
                      </div>
                    </div>
                    <div className="flex items-center space-x-2">
                      <button
                        onClick={() => copyToClipboard(selectedFileContent.content)}
                        className="p-2 bg-white/10 hover:bg-white/20 text-white rounded-lg transition-colors"
                      >
                        <Copy className="w-4 h-4" />
                      </button>
                      <span className="text-white/60 text-sm">
                        {selectedFileContent.content.split('\n').length} lines
                      </span>
                    </div>
                  </div>
                  
                  <div className="p-0">
                    <pre className="p-6 text-sm text-white/90 overflow-x-auto bg-black/20 max-h-96">
                      <code>{selectedFileContent.content}</code>
                    </pre>
                  </div>
                  
                  <div className="p-4 border-t border-white/20 bg-white/5">
                    <p className="text-white/70 text-sm">
                      <strong>Explanation:</strong> {selectedFileContent.explanation}
                    </p>
                  </div>
                </>
              )}
            </div>
          </div>

          {/* Project Stats */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
            <div className="bg-white/10 backdrop-blur-md rounded-xl p-4 border border-white/20 text-center">
              <div className="text-2xl font-bold text-blue-400">{generatedFiles.length}</div>
              <div className="text-white/60 text-sm">Total Files</div>
            </div>
            <div className="bg-white/10 backdrop-blur-md rounded-xl p-4 border border-white/20 text-center">
              <div className="text-2xl font-bold text-green-400">
                {generatedFiles.reduce((total, file) => total + file.content.split('\n').length, 0)}
              </div>
              <div className="text-white/60 text-sm">Lines of Code</div>
            </div>
            <div className="bg-white/10 backdrop-blur-md rounded-xl p-4 border border-white/20 text-center">
              <div className="text-2xl font-bold text-purple-400">{techStack.length}</div>
              <div className="text-white/60 text-sm">Technologies</div>
            </div>
            <div className="bg-white/10 backdrop-blur-md rounded-xl p-4 border border-white/20 text-center">
              <div className="text-2xl font-bold text-yellow-400">100%</div>
              <div className="text-white/60 text-sm">Production Ready</div>
            </div>
          </div>
        </>
      )}

      {/* Navigation */}
      <div className="flex justify-center space-x-4">
        <button
          onClick={onBack}
          className="bg-white/10 hover:bg-white/20 text-white px-8 py-3 rounded-xl font-semibold transition-all duration-200 border border-white/20"
        >
          Back
        </button>
        <button
          onClick={onNext}
          disabled={isGenerating}
          className="bg-gradient-to-r from-indigo-500 to-purple-600 hover:from-indigo-600 hover:to-purple-700 disabled:from-gray-500 disabled:to-gray-600 disabled:cursor-not-allowed text-white px-8 py-3 rounded-xl font-semibold transition-all duration-200 transform hover:scale-105"
        >
          Deploy to Production
        </button>
      </div>
    </div>
  );
};